#!/bin/bash

slack&

brave https://gitlab.wethinkco.de/rngobeni021/bjarne_stroustrup https://mail.google.com/mail/u/1/#inbox https://mail.google.com/mail/u/0/#inbox https://www.filmxy.vip/ https://www.youtube.com/ https://2nd.curriculum.wethinkco.de/brownfields/02-build-pipelines/stories/ https://codescene.io/projects  https://creatorapp.zohopublic.com/wtcappsite/bootcamp-manager/page-perma/Bootcamp_Admin_Portal/30MRhe6dFQxyxdOkHEfxw0PT5Xk4BvdxV2VxKgtsYTH2ST7DmbNBCSuya7yhTu5s4Cx43kdpWCxRVmmem4wtSCHqYYxbRDWaHw7P 
